// 指定proto版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: face_wake.proto

// 指定默认包名

package wake_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_face_wake_proto protoreflect.FileDescriptor

var file_face_wake_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x61, 0x63, 0x65, 0x5f, 0x77, 0x61, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x77, 0x61, 0x6b, 0x65, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x45, 0x0a, 0x0f, 0x46, 0x61,
	0x63, 0x65, 0x57, 0x61, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a,
	0x05, 0x41, 0x53, 0x6c, 0x61, 0x70, 0x12, 0x12, 0x2e, 0x77, 0x61, 0x6b, 0x65, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x77, 0x61, 0x6b,
	0x65, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x77, 0x61, 0x6b, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_face_wake_proto_goTypes = []interface{}{
	(*Request)(nil),  // 0: wake_grpc.Request
	(*Response)(nil), // 1: wake_grpc.Response
}
var file_face_wake_proto_depIdxs = []int32{
	0, // 0: wake_grpc.FaceWakeService.ASlap:input_type -> wake_grpc.Request
	1, // 1: wake_grpc.FaceWakeService.ASlap:output_type -> wake_grpc.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_face_wake_proto_init() }
func file_face_wake_proto_init() {
	if File_face_wake_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_face_wake_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_face_wake_proto_goTypes,
		DependencyIndexes: file_face_wake_proto_depIdxs,
	}.Build()
	File_face_wake_proto = out.File
	file_face_wake_proto_rawDesc = nil
	file_face_wake_proto_goTypes = nil
	file_face_wake_proto_depIdxs = nil
}
