// 指定proto版本

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: face_wake.proto

// 指定默认包名

package wake_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FaceWakeService_ASlap_FullMethodName = "/wake_grpc.FaceWakeService/ASlap"
)

// FaceWakeServiceClient is the client API for FaceWakeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaceWakeServiceClient interface {
	// 一巴掌
	ASlap(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type faceWakeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFaceWakeServiceClient(cc grpc.ClientConnInterface) FaceWakeServiceClient {
	return &faceWakeServiceClient{cc}
}

func (c *faceWakeServiceClient) ASlap(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, FaceWakeService_ASlap_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaceWakeServiceServer is the server API for FaceWakeService service.
// All implementations must embed UnimplementedFaceWakeServiceServer
// for forward compatibility
type FaceWakeServiceServer interface {
	// 一巴掌
	ASlap(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedFaceWakeServiceServer()
}

// UnimplementedFaceWakeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFaceWakeServiceServer struct {
}

func (UnimplementedFaceWakeServiceServer) ASlap(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ASlap not implemented")
}
func (UnimplementedFaceWakeServiceServer) mustEmbedUnimplementedFaceWakeServiceServer() {}

// UnsafeFaceWakeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaceWakeServiceServer will
// result in compilation errors.
type UnsafeFaceWakeServiceServer interface {
	mustEmbedUnimplementedFaceWakeServiceServer()
}

func RegisterFaceWakeServiceServer(s grpc.ServiceRegistrar, srv FaceWakeServiceServer) {
	s.RegisterService(&FaceWakeService_ServiceDesc, srv)
}

func _FaceWakeService_ASlap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceWakeServiceServer).ASlap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaceWakeService_ASlap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceWakeServiceServer).ASlap(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// FaceWakeService_ServiceDesc is the grpc.ServiceDesc for FaceWakeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaceWakeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wake_grpc.FaceWakeService",
	HandlerType: (*FaceWakeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ASlap",
			Handler:    _FaceWakeService_ASlap_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "face_wake.proto",
}
